.TH CAMMONITOR 1 "16 February 2005" "cammonitor 5.19"
.PP 
.SH "NAME" 
cammonitor \- monitor for digital cameras using the Camwire interface
.PP 
.SH "SYNOPSIS" 
.PP 
\fBcammonitor\fP [-s] [-d display_type] [-e settings_filename]
[-c chip_id_string]
.PP 
.SH "DESCRIPTION" 
.PP 
\fBcammonitor\fP provides basic access to digital cameras using the
Camwire application programmer interface (as defined in camwire.h and
camwirebus.h).  The implementation behind the Camwire interface is
currently for IEEE 1394 digital cameras conforming to the IIDC DCAM
specifications\&.
.PP
\fBcammonitor\fP has a simple text-based user interface and uses either
SDL or Xvideo to display captured frames.  On start-up, the unique ID,
vendor and model names of connected conforming cameras are displayed.
If there is more than one usable camera and no chip ID was given on the
command line, the user is prompted to choose a camera.  A menu of
one-letter commands and current status is then displayed\&.
.PP 
.SH "OPTIONS"
.PP 
.IP 
.IP "\fB-s\fP" 
Disable file sync.  By default, saved image files are synchronized with
fsync() to prevent their heaping up in user memory\&.
.IP 
.PP 
.IP 
.IP "\fB-d\fP" 
Select display type, one of NONE, SDL, or XV (case-insensitive).  The
default is SDL.  If NONE is selected, images are captured but not
displayed, and everything else still works the same way\&.
.IP 
.PP 
.IP 
.IP "\fB-e settings_filename\fP" 
On start-up, load the settings previously saved in settings_filename
with a \fBsEttings Save\fP run-time command (see below)\&.
.IP 
.PP 
.IP 
.IP "\fB-c chip_id_string\fP" 
Use the camera with the given unique chip ID.  The chip IDs of all
connected cameras are displayed if this option is not used\&.
.IP 
.PP 
.SH "RUN-TIME COMMANDS"
.PP 
All commands are case-insensitive and require a newline to execute.
Commands that require further user input may be followed by that input
on the same line, with or without separating white space\&.
.PP 
.IP 
.IP "\fBR\fP" 
Set camera to running or stopped\&.
.IP 
.IP "\fBA\fP" 
Set acquisition to continuous or single-shot.  If acquistion is
single-shot, the camera is automatically stopped after one frame and its
timestamp is displayed.  The timestamp is an estimate of the number of
seconds and fraction of a second of the frame trigger since 0 Jan 1970
as reported by the local host\&.
.IP 
.IP "\fBT\fP" 
Trigger source, internal or external\&.
.IP 
.IP "\fBP\fP" 
Trigger polarity, falling or rising\&.
.IP 
.IP "\fBI\fP" 
Integration time in seconds\&.
.IP 
.IP "\fBF\fP" 
Frame rate in frames per second\&.
.IP 
.IP "\fBZ\fP" 
Frame size, width and height pixels\&.
.IP 
.IP "\fBC\fP" 
Pixel coding, one of MONO8, YUV411, YUV422, YUV444, RGB8, MONO16, RGB16,
MONO16S, RGB16S, RAW8, or RAW16\&.
.IP 
.IP "\fBO\fP" 
Frame offset, left and top pixels\&.
.IP 
.IP "\fBW\fP" 
White balance, blue and red gain\&.
.IP 
.IP "\fBB\fP" 
Number of frame buffers\&.
.IP 
.IP "\fBD\fP" 
Shadow camera state, shadow or direct.  If set, Camwire uses its
internal records of camera status as much as possible instead of asking
the camera.  This avoids interrupting the camera while it is busy doing
other things like transmitting frames.  Turn shadowing off to get all
status information directly from the camera\&.
.IP 
.IP "\fBN\fP" 
File Name root for saved files (default cammonitor%d).  The first
occurrence of the substring "%d" in the name root will be expanded to an
11-digit frame number during the save.  If no file name extension is
given it defaults to ".ppm" (24-bit images) or ".pgm" (otherwise)\&.
.IP 
.IP "\fBL\fP" 
DeLay in seconds before saving, between the time the \fBS\fP command is
given and the time the first frame is captured for saving (default 0)\&.
.IP 
.IP "\fBM\fP" 
Multiple image saving: The number of images to save when the \fBS\fP
command is given (default 1).  If the trigger source is internal, the
frame rate determines the interval between saved images\&.
.IP 
.IP "\fBS\fP" 
Save zero, one or more frames (depending on \fBM\fP above) to the named
file (or files, with the file name optionally augmented with the frame
number, see \fBN\fP above).  Only PPM and PGM image formats are
supported at present.  The frame number and the timestamp (see \fBR\fP
above) are written as a comment in the second line of the image file.
All buffered frames are flushed and new frames are requested from the
camera for saving.  This incurs a minimum delay of about 1.5
frameperiods before the first new frame is captured, plus the
transmission delay from camera to computer\&.
.IP 
.IP "\fBE\fP" 
Settings saved/loaded to/from a file.  The settings are all the current
parameters shown on the screen.  For example, it is possible to save the
settings of a running camera and later start it up again from the
command line in the same configuration.  The settings file may also be
edited with a text editor\&.
.IP 
.IP "\fBH\fP" 
Show Camwire data, either hardware configuration or initial settings.
This is mainly for diagnostic purposes\&.
.IP 
.IP "\fBQ\fP" 
Quit from \fBcammonitor\fP\&.
.IP 
.PP 
.SH "ENVIRONMENT VARIABLES" 
.PP 
X uses the DISPLAY environment variable\&.
.PP 
Camwire uses the environment variable CAMWIRE_CONF to find a hardware
configuration for the camera\&.
.PP 
.SH "BUGS" 
.PP 
\fBCammonitor\fP will attempt to execute commands even if the camera
does not support the associated feature\&.
.PP
\fBcammonitor\fP blocks indefinitely and does not respond to commands if
it expects a frame which does not arrive for some reason\&.
.PP
When XV is selected as the display type, \fBcammonitor\fP uses an X
extension called Xvlib (Xvideo) for displaying images on the screen.  It
seems that Xvideo is not re-entrant which means that running several
instances of \fBcammonitor\fP results in scrambled image display\&.
.PP
Probably lots of other bugs, please let me know\&.
.PP 
.SH "CAVEATS" 
.PP 
All care and no responsibility. There is NO warranty; not even for
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
accompanying file COPYING for licensing information\&.
.PP 
\fBcammonitor\fP has only been tested on a small number of cameras\&.
.PP 
Nothing will happen if you try to set pixel codings that your camera does
not support\&.
.PP 
It may not be possible to set the frame rate to exactly what you want,
because it may depend on packet sizes on the camera bus.  The Camwire
interface tries to give you the nearest achievable setting which is
generally only fractionally different from the wanted value.  Only
really affects the internal trigger mode\&.
.PP 
With an external trigger the frame rate should be set higher than the
fastest anticipated external trigger frequency to avoid dropped
frames\&.
.PP 
For some types of camera bus (like IEEE 1394) frame dimensions and frame
rate are inseparable.  Changing frame dimensions may cause the frame
rate to change, although \fBcammonitor\fP tries to minimize this effect.
The available frame rates are likewise affected by the current frame
dimensions (although changing frame rate will never alter frame
dimensions)\&.
.PP 
If \fBCammonitor\fP had to be terminated because of some problem with
the camera, it may leave the camera bus still listening for a frame.
There is a tool called unlisten in the Camwire tools directory which may
help prevent unnecessary rebooting\&.
.PP 
.SH "VERSION" 
.PP 
This man page applies to cammonitor version 5\&.5\&.
.PP 
.SH "SEE ALSO" 
.PP 
The Camwire interface is described in camwire.h and camwirebus.h\&.
.PP 
.SH "DIAGNOSTICS" 
.PP 
If a bus intialization error occurs (followed by a number of reset
attempts) it probably was caused by the well-known Linux IEEE 1394 cycle
master bug (which has probably been fixed by now if this man page is
old).  If trying to run \fBcammonitor\fP still fails after several tries
then it means that no IIDC DCAM-compatible camera was found\&.
.PP 
If Camwire cannot find configuration or settings files, it will display
verbose error messages which guide the user through the process of
creating the necessary files\&.
.PP 
If Camwire was compiled with the CAMWIRE_DEBUG macro defined, more
verbose error messages are printed when things do not work.  The most
common case is when a camera does not support features such as an
external trigger or trigger polarity.  Such messages are generally
harmless though admittedly annoying.  The CAMWIRE_DEBUG macro can be
removed by editing a Camwire Makefile\&.
.PP 
.SH "AUTHOR" 
.PP 
Johann Schoonees j\&.schoonees@irl\&.cri\&.nz\&.
.PP 
