#emacs, this is -*-Python-*- mode
Import('backend','env','cam_iface_external_libs',
       'cam_iface_external_libpath',
       'cam_iface_external_cpppath',
       'cam_iface_static_lib', 'cam_iface_shared_lib',
       'cam_iface_env_kwargs')

shmwrap_obj = env.Object(target='shmwrap_%s'%backend,
                         source=['shmwrap.c'],
                         LIBS=cam_iface_external_libs+[cam_iface_static_lib],
                         LIBPATH=cam_iface_external_libpath,
                         CPPPATH=['../inc']+cam_iface_external_cpppath,
                         **cam_iface_env_kwargs)
env.Program(target='shmwrap_%s'%backend,
            #source=shmwrap_obj,
            source=shmwrap_obj+['_shmwrap_state.c'],
            LIBS=cam_iface_external_libs+[cam_iface_static_lib],
            LIBPATH=cam_iface_external_libpath,
            CPPPATH=['../inc'],
            **cam_iface_env_kwargs)
