#emacs, this is -*-Python-*- mode
import os

Import('backend','env','cam_iface_external_libs',
       'cam_iface_external_libpath',
       'cam_iface_external_cpppath',
       'cam_iface_external_linkflags',
       'cam_iface_static_lib', 'cam_iface_shared_lib',
       'cam_iface_env_kwargs', 'bin_output_dir')

simple_obj = env.Object(target='simple_%s'%backend,
                        source=['simple.c'],
                        LIBS=cam_iface_external_libs+[cam_iface_static_lib],
                        LIBPATH=cam_iface_external_libpath,
                        CPPPATH=['../inc']+cam_iface_external_cpppath,
                        LINKFLAGS=cam_iface_external_linkflags,
                        **cam_iface_env_kwargs)
env.Program(target=os.path.join(bin_output_dir,'simple_%s'%backend),
            source=simple_obj,
            LIBS=cam_iface_external_libs+[cam_iface_static_lib],
            LIBPATH=cam_iface_external_libpath,
            CPPPATH=['../inc'],
            LINKFLAGS=cam_iface_external_linkflags,
            **cam_iface_env_kwargs)

###
if 1:
    multicam_obj = env.Object(target='multi-cam-%s'%backend,
                            source=['multi-cam.c'],
                            LIBS=cam_iface_external_libs+[cam_iface_static_lib],
                            LIBPATH=cam_iface_external_libpath,
                            CPPPATH=['../inc']+cam_iface_external_cpppath,
                            LINKFLAGS=cam_iface_external_linkflags,
                            **cam_iface_env_kwargs)
    env.Program(target=os.path.join(bin_output_dir,'multi-cam-%s'%backend),
                source=multicam_obj,
                LIBS=cam_iface_external_libs+[cam_iface_static_lib],
                LIBPATH=cam_iface_external_libpath,
                CPPPATH=['../inc'],
                LINKFLAGS=cam_iface_external_linkflags,
                **cam_iface_env_kwargs)

###
if 1:
    cvlibs = ['cv','highgui']

    opencv_obj = env.Object(target='opencv_%s'%backend,
                            source=['opencv.c'],
                            LIBS=cam_iface_external_libs+[cam_iface_static_lib],
                            LIBPATH=cam_iface_external_libpath,
                            CPPPATH=['../inc']+cam_iface_external_cpppath,
                            LINKFLAGS=cam_iface_external_linkflags,
                            **cam_iface_env_kwargs)
    env.Program(target=os.path.join(bin_output_dir,'opencv_%s'%backend),
                source=opencv_obj,
                LIBS=cam_iface_external_libs+[cam_iface_static_lib]+cvlibs,
                LIBPATH=cam_iface_external_libpath,
                CPPPATH=['../inc'],
                LINKFLAGS=cam_iface_external_linkflags,
                **cam_iface_env_kwargs)

