Import('backend','env','cam_iface_external_libs',
       'cam_iface_external_libpath',
       'cam_iface_external_cpppath',
       'cam_iface_env_kwargs')

simple_obj = env.Object(target='simple_%s'%backend,
                        source=['simple.c'],
                        LIBS=cam_iface_external_libs,
                        LIBPATH=cam_iface_external_libpath,
                        CPPPATH=['../inc']+cam_iface_external_cpppath,
                        **cam_iface_env_kwargs)
env.Program(target='simple_%s'%backend,
            source=simple_obj,
            LIBS=cam_iface_external_libs,
            LIBPATH=cam_iface_external_libpath,
            CPPPATH=['../inc'],
            **cam_iface_env_kwargs)

if 0:
    env.Program(target='simple_fast_%s'%backend,
                source=['simple_fast.c'],
                LIBS=cam_iface_external_libs,
                LIBPATH=cam_iface_external_libpath,
                CPPPATH=['../inc'],
                **cam_iface_env_kwargs)
