/* Generated by Pyrex 0.9.5.1a on Fri Nov  2 16:55:17 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "shmwrap.h"
#include "stdlib.h"
#include "math.h"
#include "ads_wrap_system.h"
#include "stdio.h"
#include "sys/ipc.h"
#include "sys/shm.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from c_lib */


/* Declarations from c_python */


/* Declarations from c_lib_shm */


/* Declarations from _cam_iface_shm */

typedef struct {
  int two;
  int nd;
  char typekind;
  int itemsize;
  int flags;
  Py_intptr_t (*shape);
  Py_intptr_t (*strides);
  void (*data);
} __pyx_t_14_cam_iface_shm_PyArrayInterface;


struct __pyx_obj_14_cam_iface_shm_ShmManager {
  PyObject_HEAD
  char (*data);
};

static PyTypeObject *__pyx_ptype_14_cam_iface_shm_ShmManager = 0;
static shmwrap_msg_ready_t __pyx_v_14_cam_iface_shm__tmp_curmsg;
static struct __pyx_obj_14_cam_iface_shm_ShmManager *__pyx_v_14_cam_iface_shm__shm_manager;
static PyObject *__pyx_k4;
static char (*(__pyx_f_14_cam_iface_shm__get_shm_pointer(void))); /*proto*/


/* Implementation of _cam_iface_shm */


static PyObject *__pyx_n_c_lib;
static PyObject *__pyx_n_c_python;
static PyObject *__pyx_n_c_lib_shm;
static PyObject *__pyx_n_sys;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n_perror;
static PyObject *__pyx_n_shmwrap_msg_ready_t_size;
static PyObject *__pyx_n_shmwrap_frame_ready_port_;
static PyObject *__pyx_n_shmwrap_control_port_;
static PyObject *__pyx_n_Stuff;
static PyObject *__pyx_n_buf2class;
static PyObject *__pyx_n_get_data_copy;

static PyObject *__pyx_f_14_cam_iface_shm_perror(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_cam_iface_shm_perror(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_msg = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"msg",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_msg)) return 0;
  Py_INCREF(__pyx_v_msg);

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":42 */
  if (__Pyx_PrintItem(__pyx_v_msg) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_cam_iface_shm.perror");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_msg);
  return __pyx_r;
}

static PyObject *__pyx_n_ftok;
static PyObject *__pyx_n_exit;
static PyObject *__pyx_n_shmget;
static PyObject *__pyx_n_shmat;


static char (*__pyx_f_14_cam_iface_shm__get_shm_pointer(void)) {
  key_t __pyx_v_key;
  int __pyx_v_shmid;
  char (*__pyx_v_data);
  char (*__pyx_r);
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":50 */
  __pyx_v_key = ftok(shmwrap_ftok_path,shmwrap_shm_name);

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":52 */
  __pyx_1 = (__pyx_v_key == (-1));
  if (__pyx_1) {

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":53 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_perror); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_INCREF(__pyx_n_ftok);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_ftok);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":54 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_sys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_exit); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_4 = PyInt_FromLong(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
    __pyx_4 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":56 */
  __pyx_v_shmid = shmget(__pyx_v_key,shm_size,0644);

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":57 */
  __pyx_1 = (__pyx_v_shmid == (-1));
  if (__pyx_1) {

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":58 */
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_perror); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_INCREF(__pyx_n_shmget);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_n_shmget);
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":59 */
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_sys); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_exit); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_4 = PyInt_FromLong(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
    __pyx_4 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":61 */
  __pyx_v_data = ((char (*))shmat(__pyx_v_shmid,((void (*))0),SHM_RDONLY));

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":62 */
  __pyx_1 = (__pyx_v_data == ((char (*))(-1)));
  if (__pyx_1) {

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":63 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_perror); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_INCREF(__pyx_n_shmat);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_shmat);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":64 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_sys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_exit); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_4 = PyInt_FromLong(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
    __pyx_4 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":66 */
  __pyx_r = __pyx_v_data;
  goto __pyx_L0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("_cam_iface_shm._get_shm_pointer");
  __pyx_L0:;
  return __pyx_r;
}

static int __pyx_f_14_cam_iface_shm_10ShmManager___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_14_cam_iface_shm_10ShmManager___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":71 */
  ((struct __pyx_obj_14_cam_iface_shm_ShmManager *)__pyx_v_self)->data = __pyx_f_14_cam_iface_shm__get_shm_pointer();

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_cam_id;
static PyObject *__pyx_n_sendnumber;
static PyObject *__pyx_n_framenumber;
static PyObject *__pyx_n_width;
static PyObject *__pyx_n_height;
static PyObject *__pyx_n_roi_x;
static PyObject *__pyx_n_roi_y;
static PyObject *__pyx_n_timestamp;
static PyObject *__pyx_n_start_offset;
static PyObject *__pyx_n_stride;

static PyObject *__pyx_f_14_cam_iface_shm_buf2class(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_cam_iface_shm_buf2class(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_buf = 0;
  char (*__pyx_v_cbuf);
  shmwrap_msg_ready_t (*__pyx_v_pack);
  PyObject *__pyx_v_result;
  PyObject *__pyx_r;
  char (*__pyx_1);
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"buf",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_buf)) return 0;
  Py_INCREF(__pyx_v_buf);
  __pyx_v_result = Py_None; Py_INCREF(Py_None);

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":89 */
  __pyx_1 = PyString_AsString(__pyx_v_buf); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_v_cbuf = __pyx_1;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":90 */
  __pyx_v_pack = ((shmwrap_msg_ready_t (*))(&(__pyx_v_cbuf[0])));

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":91 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Stuff); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_result);
  __pyx_v_result = __pyx_3;
  __pyx_3 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":92 */
  __pyx_2 = PyInt_FromLong(__pyx_v_pack->cam_id); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_cam_id, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":93 */
  __pyx_3 = PyInt_FromLong(__pyx_v_pack->sendnumber); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_sendnumber, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":94 */
  __pyx_2 = PyInt_FromLong(__pyx_v_pack->framenumber); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_framenumber, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":95 */
  __pyx_3 = PyInt_FromLong(__pyx_v_pack->width); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_width, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":96 */
  __pyx_2 = PyInt_FromLong(__pyx_v_pack->height); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_height, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":97 */
  __pyx_3 = PyInt_FromLong(__pyx_v_pack->roi_x); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_roi_x, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":98 */
  __pyx_2 = PyInt_FromLong(__pyx_v_pack->roi_y); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_roi_y, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":99 */
  __pyx_3 = PyFloat_FromDouble(__pyx_v_pack->timestamp); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_timestamp, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":100 */
  __pyx_2 = PyInt_FromLong(__pyx_v_pack->start_offset); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_start_offset, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":101 */
  __pyx_3 = PyInt_FromLong(__pyx_v_pack->stride); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_result, __pyx_n_stride, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":102 */
  Py_INCREF(__pyx_v_result);
  __pyx_r = __pyx_v_result;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_cam_iface_shm.buf2class");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_buf);
  return __pyx_r;
}

static PyObject *__pyx_n_asarray;
static PyObject *__pyx_n_len;
static PyObject *__pyx_n_shape;
static PyObject *__pyx_n_dtype;
static PyObject *__pyx_n_uint8;
static PyObject *__pyx_n_strides;
static PyObject *__pyx_n___array_struct__;
static PyObject *__pyx_n_fromstring;


static PyObject *__pyx_f_14_cam_iface_shm_get_data_copy(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_14_cam_iface_shm_get_data_copy(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_curmsg = 0;
  PyObject *__pyx_v_optional_preallocated_buf = 0;
  char (*__pyx_v_source_ptr);
  int __pyx_v_size;
  unsigned long __pyx_v_start_offset;
  int __pyx_v_row;
  int __pyx_v_width;
  int __pyx_v_height;
  int __pyx_v_source_stride;
  int __pyx_v_dest_stride;
  __pyx_t_14_cam_iface_shm_PyArrayInterface (*__pyx_v_inter);
  PyObject *__pyx_v_result;
  PyObject *__pyx_v_hold_onto_until_done_with_array;
  PyObject *__pyx_v_buf;
  PyObject *__pyx_v_result1;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  unsigned long __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"curmsg","optional_preallocated_buf",0};
  __pyx_v_optional_preallocated_buf = __pyx_k4;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_curmsg, &__pyx_v_optional_preallocated_buf)) return 0;
  Py_INCREF(__pyx_v_curmsg);
  Py_INCREF(__pyx_v_optional_preallocated_buf);
  __pyx_v_result = Py_None; Py_INCREF(Py_None);
  __pyx_v_hold_onto_until_done_with_array = Py_None; Py_INCREF(Py_None);
  __pyx_v_buf = Py_None; Py_INCREF(Py_None);
  __pyx_v_result1 = Py_None; Py_INCREF(Py_None);

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":116 */
  __pyx_1 = __pyx_v_optional_preallocated_buf != Py_None;
  if (__pyx_1) {

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":117 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_asarray); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
    Py_INCREF(__pyx_v_optional_preallocated_buf);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_optional_preallocated_buf);
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_optional_preallocated_buf);
    __pyx_v_optional_preallocated_buf = __pyx_4;
    __pyx_4 = 0;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":118 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_v_optional_preallocated_buf, __pyx_n_shape); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = PyInt_FromLong(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_2, __pyx_3, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    __pyx_1 = __pyx_1 == 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (!__pyx_1) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
    }

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":119 */
    __pyx_4 = PyObject_GetAttr(__pyx_v_optional_preallocated_buf, __pyx_n_shape); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_4, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_4 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_height); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_3, __pyx_4, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    __pyx_1 = __pyx_1 == 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (!__pyx_1) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    }

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":120 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_optional_preallocated_buf, __pyx_n_shape); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_width); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_4, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    __pyx_1 = __pyx_1 >= 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (!__pyx_1) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
    }

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":121 */
    __pyx_3 = PyObject_GetAttr(__pyx_v_optional_preallocated_buf, __pyx_n_dtype); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_4, __pyx_n_uint8); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (PyObject_Cmp(__pyx_3, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
    __pyx_1 = __pyx_1 == 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (!__pyx_1) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
    }

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":122 */
    __pyx_4 = PyObject_GetAttr(__pyx_v_optional_preallocated_buf, __pyx_n_strides); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
    __pyx_2 = PyObject_GetItem(__pyx_4, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_dest_stride = __pyx_1;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":124 */
  __pyx_4 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_width); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_width = __pyx_1;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":125 */
  __pyx_3 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_height); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_height = __pyx_1;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":126 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_stride); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_v_source_stride = __pyx_1;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":127 */
  __pyx_4 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_start_offset); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_5 = PyInt_AsUnsignedLongMask(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_start_offset = __pyx_5;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":129 */
  __pyx_v_source_ptr = (__pyx_v_14_cam_iface_shm__shm_manager->data + __pyx_v_start_offset);

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":130 */
  __pyx_v_size = (__pyx_v_height * __pyx_v_source_stride);

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":132 */
  __pyx_1 = __pyx_v_optional_preallocated_buf != Py_None;
  if (__pyx_1) {

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":133 */
    Py_INCREF(__pyx_v_optional_preallocated_buf);
    Py_DECREF(__pyx_v_result);
    __pyx_v_result = __pyx_v_optional_preallocated_buf;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":135 */
    __pyx_3 = PyObject_GetAttr(__pyx_v_result, __pyx_n___array_struct__); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
    Py_DECREF(__pyx_v_hold_onto_until_done_with_array);
    __pyx_v_hold_onto_until_done_with_array = __pyx_3;
    __pyx_3 = 0;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":136 */
    __pyx_v_inter = ((__pyx_t_14_cam_iface_shm_PyArrayInterface (*))PyCObject_AsVoidPtr(__pyx_v_hold_onto_until_done_with_array));

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":137 */
    if (!(__pyx_v_inter->two == 2)) {
      PyErr_SetNone(PyExc_AssertionError);
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
    }

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":141 */
    for (__pyx_v_row = 0; __pyx_v_row < __pyx_v_height; ++__pyx_v_row) {

      /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":145 */
      memcpy((__pyx_v_inter->data + (__pyx_v_row * __pyx_v_dest_stride)),(__pyx_v_source_ptr + (__pyx_v_row * __pyx_v_source_stride)),__pyx_v_width);
    }
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":149 */
    __pyx_2 = PyString_FromStringAndSize(__pyx_v_source_ptr,__pyx_v_size); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    Py_DECREF(__pyx_v_buf);
    __pyx_v_buf = __pyx_2;
    __pyx_2 = 0;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":150 */
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_fromstring); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    Py_INCREF(__pyx_v_buf);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_buf);
    __pyx_4 = PyDict_New(); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    __pyx_7 = PyObject_GetAttr(__pyx_6, __pyx_n_uint8); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    if (PyDict_SetItem(__pyx_4, __pyx_n_dtype, __pyx_7) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_6 = PyEval_CallObjectWithKeywords(__pyx_3, __pyx_2, __pyx_4); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_result1);
    __pyx_v_result1 = __pyx_6;
    __pyx_6 = 0;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":151 */
    __pyx_7 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_height); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_stride); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_7);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_3);
    __pyx_7 = 0;
    __pyx_3 = 0;
    if (PyObject_SetAttr(__pyx_v_result1, __pyx_n_shape, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":152 */
    __pyx_4 = PySlice_New(Py_None, Py_None, Py_None); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    __pyx_6 = PyObject_GetAttr(__pyx_v_curmsg, __pyx_n_width); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    __pyx_7 = PySlice_New(Py_None, __pyx_6, Py_None); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
    PyTuple_SET_ITEM(__pyx_3, 1, __pyx_7);
    __pyx_4 = 0;
    __pyx_7 = 0;
    __pyx_2 = PyObject_GetItem(__pyx_v_result1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_result);
    __pyx_v_result = __pyx_2;
    __pyx_2 = 0;
  }
  __pyx_L3:;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":153 */
  Py_INCREF(__pyx_v_result);
  __pyx_r = __pyx_v_result;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("_cam_iface_shm.get_data_copy");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_hold_onto_until_done_with_array);
  Py_DECREF(__pyx_v_buf);
  Py_DECREF(__pyx_v_result1);
  Py_DECREF(__pyx_v_curmsg);
  Py_DECREF(__pyx_v_optional_preallocated_buf);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Stuff, "Stuff"},
  {&__pyx_n___array_struct__, "__array_struct__"},
  {&__pyx_n_asarray, "asarray"},
  {&__pyx_n_buf2class, "buf2class"},
  {&__pyx_n_c_lib, "c_lib"},
  {&__pyx_n_c_lib_shm, "c_lib_shm"},
  {&__pyx_n_c_python, "c_python"},
  {&__pyx_n_cam_id, "cam_id"},
  {&__pyx_n_dtype, "dtype"},
  {&__pyx_n_exit, "exit"},
  {&__pyx_n_framenumber, "framenumber"},
  {&__pyx_n_fromstring, "fromstring"},
  {&__pyx_n_ftok, "ftok"},
  {&__pyx_n_get_data_copy, "get_data_copy"},
  {&__pyx_n_height, "height"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_numpy, "numpy"},
  {&__pyx_n_perror, "perror"},
  {&__pyx_n_roi_x, "roi_x"},
  {&__pyx_n_roi_y, "roi_y"},
  {&__pyx_n_sendnumber, "sendnumber"},
  {&__pyx_n_shape, "shape"},
  {&__pyx_n_shmat, "shmat"},
  {&__pyx_n_shmget, "shmget"},
  {&__pyx_n_shmwrap_control_port_, "shmwrap_control_port_"},
  {&__pyx_n_shmwrap_frame_ready_port_, "shmwrap_frame_ready_port_"},
  {&__pyx_n_shmwrap_msg_ready_t_size, "shmwrap_msg_ready_t_size"},
  {&__pyx_n_start_offset, "start_offset"},
  {&__pyx_n_stride, "stride"},
  {&__pyx_n_strides, "strides"},
  {&__pyx_n_sys, "sys"},
  {&__pyx_n_timestamp, "timestamp"},
  {&__pyx_n_uint8, "uint8"},
  {&__pyx_n_width, "width"},
  {0, 0}
};

static PyObject *__pyx_tp_new_14_cam_iface_shm_ShmManager(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  return o;
}

static void __pyx_tp_dealloc_14_cam_iface_shm_ShmManager(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_14_cam_iface_shm_ShmManager(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_14_cam_iface_shm_ShmManager(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_14_cam_iface_shm_ShmManager[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ShmManager = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_ShmManager = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ShmManager = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ShmManager = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_14_cam_iface_shm_ShmManager = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_cam_iface_shm.ShmManager", /*tp_name*/
  sizeof(struct __pyx_obj_14_cam_iface_shm_ShmManager), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_14_cam_iface_shm_ShmManager, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_ShmManager, /*tp_as_number*/
  &__pyx_tp_as_sequence_ShmManager, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ShmManager, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ShmManager, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_14_cam_iface_shm_ShmManager, /*tp_traverse*/
  __pyx_tp_clear_14_cam_iface_shm_ShmManager, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_14_cam_iface_shm_ShmManager, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_14_cam_iface_shm_10ShmManager___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_14_cam_iface_shm_ShmManager, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"perror", (PyCFunction)__pyx_f_14_cam_iface_shm_perror, METH_VARARGS|METH_KEYWORDS, 0},
  {"buf2class", (PyCFunction)__pyx_f_14_cam_iface_shm_buf2class, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_data_copy", (PyCFunction)__pyx_f_14_cam_iface_shm_get_data_copy, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_cam_iface_shm(void); /*proto*/
PyMODINIT_FUNC init_cam_iface_shm(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_cam_iface_shm", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_v_14_cam_iface_shm__shm_manager = ((struct __pyx_obj_14_cam_iface_shm_ShmManager *)Py_None); Py_INCREF(Py_None);
  if (PyType_Ready(&__pyx_type_14_cam_iface_shm_ShmManager) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ShmManager", (PyObject *)&__pyx_type_14_cam_iface_shm_ShmManager) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_ptype_14_cam_iface_shm_ShmManager = &__pyx_type_14_cam_iface_shm_ShmManager;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":8 */
  __pyx_1 = __Pyx_Import(__pyx_n_sys, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sys, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":9 */
  __pyx_1 = __Pyx_Import(__pyx_n_numpy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_numpy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":74 */
  __pyx_1 = PyInt_FromLong((sizeof(__pyx_v_14_cam_iface_shm__tmp_curmsg))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_shmwrap_msg_ready_t_size, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":76 */
  __pyx_1 = PyInt_FromLong(shmwrap_frame_ready_port); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_shmwrap_frame_ready_port_, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":77 */
  __pyx_1 = PyInt_FromLong(shmwrap_control_port); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_shmwrap_control_port_, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":80 */
  __pyx_1 = PyObject_CallObject(((PyObject*)__pyx_ptype_14_cam_iface_shm_ShmManager), 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_14_cam_iface_shm_ShmManager)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_14_cam_iface_shm__shm_manager));
  __pyx_v_14_cam_iface_shm__shm_manager = ((struct __pyx_obj_14_cam_iface_shm_ShmManager *)__pyx_1);
  __pyx_1 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":82 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_Stuff, "_cam_iface_shm"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":83 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Stuff, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":104 */
  Py_INCREF(Py_None);
  __pyx_k4 = Py_None;

  /* "/home/astraw/fn/motmot/cam_iface/src/_cam_iface_shm.pyx":156 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_cam_iface_shm");
}

static char *__pyx_filenames[] = {
  "_cam_iface_shm.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        int len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
